[tool.pyflow]
name = "Calculator"
py_version = "3.8"
version = "0.0.9"
author = "David O'Connor"

[tool.pyflow.dependencies]
numpy = "^1.18.1"
scipy = "^1.4.1"
matplotlib = "^3.1.3"
ipython = {version = "^7.13.0", extras= ["qtconsole"]}
pyqt5 = "^5.14.1"
# spyder = "^3.3.6"
scinot = "^0.0.5"
fplot = "^0.1.1"
sympy = "^1.5.1"
pywin32 = "^227.0.0"
siunits = "^0.0.6"
jupyterlab = "^2.0.0"

[tool.pyflow.dev-dependencies]

